---
title: "Unit11_Prelive"
author: "Richard Palmer"
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fpp)
```

# Activity Three
```{r}
# Seasonal Trend

## Load the data

data("austourists")

## Read about the dataset!

?austourists


## Always plot the data first!

plot(austourists,main="Original data",xlab="year",ylab="Austrailian Tourists")

## returns a ts object.  

aust = window(austourists,start = 1999, end = 2004)

## fit an additive and multiplicative model

fit1s = hw(aust,seasonal = "additive",h = 40)
fit2s = hw(aust,seasonal = "multiplicative",h = 40)


## Plot the original data

plot(aust,ylab = "Australian Tourists",
     xlab = "Year",
     type = "o",
     xlim = c(1999, 2014),ylim = c(15,60),
     main="Fitting Seasonal Trends")

## add the fitted values from the model (of the training data)

lines(fitted(fit1s),col = "blue", type= "o")
lines(fitted(fit2s), col = "red", type= "o")

## Now add the forecasts (add these one at a time)

lines(fit1s$mean, col = "blue", type= "o")
lines(fit2s$mean,col = "red", type= "o")


## Compare the accuracy

accuracy(fit1s,austourists)
accuracy(fit2s,austourists)

## add the actual values to visually compare the forecasts to the actual values. 

points(austourists, type = "o")
legend(1999,60,
       legend=c("original","additive","multiplicative"),
       col=c("black","blue","red"),
       lty=1)

```