---
title: "Unit5 PreLive"
author: "Richard Palmer"
date: "9/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# get libraries
library(dplyr)
library(ggplot2)
library(plotly)
library(ggalt)
library(ggcorrplot)
library(tidyr)
library(stringr)
```

# Part 1

## Get the data and compute height in inches
```{r}
# load data
raw_ball <- read.csv(file="PlayersBBall.csv")
# convert height to inches, compute years played
BBall <- raw_ball %>% mutate(htc=as.character(height)) %>%
  mutate (TotalInches = 12*as.numeric(str_extract(htc,"^[:digit:]+")) + as.numeric(str_extract(htc,"[:digit:]+$")) )
BBall$position <- as.factor(BBall$position)
```

## histogram of heights
```{r}
BBall %>% drop_na(TotalInches) %>% ggplot(aes(x=TotalInches,color=position)) + 
  geom_histogram() + facet_wrap(~position) + ggtitle('Histograms of Height in inches, by position')
```

# Part 2

## Get the data, drop observations for which we cannot compute height or weight
```{r}
fifa_raw <- read.csv(file='FIFA Players.csv')
FIFA <- fifa_raw %>% mutate(htc=as.character(Height)) %>% mutate(wtc=as.character(Weight)) %>%
  mutate (TotalInches = 12*as.numeric(str_extract(htc,"^[:digit:]+")) + as.numeric(str_extract(htc,"[:digit:]+$")) ) %>%
  mutate (TotalPounds = as.numeric(str_extract(wtc,"^[:digit:]+"))) 
```

## Try a little EDA
```{r}
FIFA %>% drop_na(TotalInches) %>% drop_na(TotalPounds) %>% ggplot(aes(x=TotalInches,y=TotalPounds)) + geom_point() + facet_wrap(~Position)
```

## limit to only LB and LM positions
```{r}
FIFA %>% filter(grepl("(LM|LB)",Position)) %>% drop_na(TotalInches) %>% drop_na(TotalPounds) %>%
  ggplot(aes(x=TotalInches,y=TotalPounds)) + geom_point() + facet_wrap(~Position)
```

# Part 3

## load the data
```{r}
yob2016 <- read.csv(file='yob2016.txt',header=FALSE,sep=";")
names(yob2016) <- c("name","gender","count")
summary(yob2016)
str(yob2016)
```

## find the misspelling
```{r}
bad <- yob2016 %>% filter(grepl("yyy$",name,ignore.case = TRUE))
as.character(bad$name)
```
